# 随机数组

`NumPy`中的随机数组是通过子模块`numpy.random`实现的：

In [1]:
import numpy as np

函数`np.random.rand()`可以用来生成0到1之间指定大小的的随机数组：

In [2]:
np.random.rand(2, 3)

array([[0.89610076, 0.20257692, 0.05524905],
       [0.31842817, 0.37202256, 0.06250122]])

函数`np.random.randn()`生成的则是服从标准正态分布的随机数组：

In [3]:
np.random.randn(2, 3)

array([[-0.1460316 , -0.38227228, -0.57246999],
       [ 1.64077195, -0.48344866,  1.78002085]])

与标准模块`random`类似，`numpy.random`也有`choice()`函数，不过功能更强大。

```python
np.random.choice(a, size=None, replace=True, p=None)
```

该函数从一维数组或列表a中，随机选取出size大小形状的数组成数组。其中，replace参数表示选择的元素是否可重复，p是一个与a大小相同的数组，表示a中各个元素被选中的概率，默认为等概率：


In [4]:
np.random.choice(range(3), (2, 3))

array([[2, 0, 2],
       [0, 1, 1]])

`np.random.shuffle()`函数支持对数组的乱序操作：

In [5]:
a = np.arange(6)

In [6]:
np.random.shuffle(a)

In [7]:
a

array([2, 1, 3, 5, 4, 0])